language: python
sudo: required
dist: xenial

matrix:
  include:
    - python: "2.7"
      env: PYTHONVER=2
    - python: "3.6"
      env: PYTHONVER=3

install:
    - pip install -e .[dev]

script:
  - if [ "$PYTHONVER" = "3" ]; then echo "Python3" && make test; fi
# - if [ "$PYTHONVER" = "2" ]; then echo "Python2" && make testpy2; fi


after_success:
    - codecov --token f87444f1-1c2d-4f8d-9f54-14089c09c18c

branches:
  only:
  - master

notifications:
  email: false
